version: '3.7'

services: 
    elasticsearch:
        image: elasticsearch:8.6.2
        ports:
            - "${DB_PORT}:9200"
            - "${DB_SND_PORT}:9300"
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        
    redis:
        image: redis
        ports:
            - "${REDIS_PORT}:6379"