version: '3.7'

services: 
    elasticsearch:
        image: elasticsearch:8.6.2
        ports:
            - "${DB_PORT}:9200"
            - "${DB_SND_PORT}:9300"
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        
    redis:
        image: redis
        ports:
            - "${REDIS_PORT}:6379"

    #app:
    #    image: app
    #    environment: 
    #        - REDIS_HOST=redis
    #        - REDIS_PORT=${REDIS_PORT}
    #        - DB_HOST=http://elasticsearch:${DB_PORT}/
    #        - API_URL=${API_URL}
    #        - APP_PORT=${APP_PORT}
    #    depends_on:
    #        - elasticsearch
    #        - redis
    #    build: 
    #        context: .
    #    ports: 
    #        - "${APP_PORT}:3000"
    #    links:
    #        - redis
    #        - elasticsearch